In [33]:
import numpy as np

In [34]:
ls = [[1233,11,233,3445,1223], [121,2324], [232, 1221, 2345]]

In [35]:
ls

[[1233, 11, 233, 3445, 1223], [121, 2324], [232, 1221, 2345]]

In [36]:
n =np.arange(27)

In [37]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [38]:
type(n)

numpy.ndarray

In [39]:
n = n.reshape(3,9)                  # 2 Dimensional arrays

n

In [40]:
print(n)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


In [41]:
n = n.reshape(3,3,3)              # 3 Dimensional arrays

In [42]:
print(n)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [43]:
# Converting list into arrays using 'AsArray method

In [44]:
m = np.asarray(ls)

In [45]:
m

array([[1233, 11, 233, 3445, 1223], [121, 2324], [232, 1221, 2345]], dtype=object)

In [46]:
print(m)

[[1233, 11, 233, 3445, 1223] [121, 2324] [232, 1221, 2345]]


In [47]:
print(m[0])

[1233, 11, 233, 3445, 1223]


In [48]:
import cv2

In [49]:
im_g = cv2.imread("smallgray.png",0)

In [50]:
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [59]:
print(im_g[1,2:4])

[[255 255 255]
 [255 255 255]]


In [53]:
im_g = cv2.imread("smallgray.png", 1)

In [63]:
print(im_g[1,2:3])

[[255 255 255]]


In [55]:
# Indexing and slicing the numpy arrays

In [58]:
print(im_g[1,1,1:])

[125 125]


In [61]:
print(im_g.shape)

(3, 5, 3)


In [64]:

## Iterating numpy arrays


In [65]:
for e in im_g:
    print(e)

[[187 187 187]
 [158 158 158]
 [104 104 104]
 [121 121 121]
 [143 143 143]]
[[198 198 198]
 [125 125 125]
 [255 255 255]
 [255 255 255]
 [147 147 147]]
[[209 209 209]
 [134 134 134]
 [255 255 255]
 [ 97  97  97]
 [182 182 182]]


In [68]:
#  Iterating through columns 

In [69]:
for e in im_g.T:
    print(e)

[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]
[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]
[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]


In [67]:
for e in im_g.flat:
    print(e)

187
187
187
158
158
158
104
104
104
121
121
121
143
143
143
198
198
198
125
125
125
255
255
255
255
255
255
147
147
147
209
209
209
134
134
134
255
255
255
97
97
97
182
182
182


In [71]:
im_g = cv2.imread("smallgray.png", 0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [72]:
# Splitting and concaternating the numpy arrays ( Horizonatal stack and Vertical Stack)

In [73]:
hs = np.hstack((im_g, im_g))

In [74]:
print(hs)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [75]:
vs = np.vstack((im_g, im_g))

In [76]:
print(vs)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [87]:
#Splitting the arrays

In [88]:
print(hs)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [86]:
hsplt = np.hsplit(hs,5)
print(hsplt)

[array([[187, 158],
       [198, 125],
       [209, 134]], dtype=uint8), array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8), array([[143, 187],
       [147, 198],
       [182, 209]], dtype=uint8), array([[158, 104],
       [125, 255],
       [134, 255]], dtype=uint8), array([[121, 143],
       [255, 147],
       [ 97, 182]], dtype=uint8)]


In [93]:
vsplt = np.vsplit(hs,3)
print(vsplt)

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]
